import { DashboardEntry, DashboardEntryStatus } from '@transveho-core';

export const ELEMENT_DATA_1: DashboardEntry[] = [
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.canceled,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.pending,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.canceled,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.pending,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  }
];

export const ELEMENT_DATA_2: DashboardEntry[] = [
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Seby',
    passengerName: 'Beby',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.canceled,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.pending,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.canceled,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.pending,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  },
  {
    date: '04/22/2020 13:14',
    passengerSurname: 'Maria',
    passengerName: 'Pavel',
    passengerPhoneNumber: '1234567890123',
    transferDate: '04/22/2020',
    route: 'TIMISOARA-ARAD',
    planeHour: '11:30',
    status: DashboardEntryStatus.completed,
    // details
    pickupAddress: 'Calea Victoriei, nr3',
    nrOfPersons: '1 adult',
    notes: 'trebuie factura',
    deliveryAddress: 'Aeroport traian vuia',
    paymentMethod: '150 lei',
    beneficiary: '',
    transporter: '-CRISTI',
    car: '-CRISTI'
  }
];
